[Paths]
Prefix=../
Documentation=doc
Headers=include
Libraries=lib
LibraryExecutables=bin
Binaries=bin
Plugins=plugins
QmlImports=qml
ArchData=.
Data=.
Translations=translations
Examples=examples
Tests=tests
Settings=etc/xdg
HostPrefix=../../../qt6
HostBinaries=bin
HostLibraries=lib
HostLibraryExecutables=libexec
HostData=../x86_64-w64-mingw32/qt6
Sysroot=
SysrootifyPrefix=false
TargetSpec=win32-g++
HostSpec=
