QT.network_private.VERSION = 6.7.3
QT.network_private.name = QtNetwork
QT.network_private.module =
QT.network_private.libs = $$QT_MODULE_LIB_BASE
QT.network_private.includes = $$QT_MODULE_INCLUDE_BASE/QtNetwork/6.7.3 $$QT_MODULE_INCLUDE_BASE/QtNetwork/6.7.3/QtNetwork
QT.network_private.frameworks = 
QT.network_private.depends = core_private network
QT.network_private.uses = 
QT.network_private.module_config = v2 internal_module
QT.network_private.enabled_features = system-proxies networklistmanager publicsuffix-qt
QT.network_private.disabled_features = libresolv libproxy linux-netlink res_setservers publicsuffix-system
QMAKE_INCDIR_LIBPROXY = //scratch/build/mxe-octave-w64/usr/x86_64-w64-mingw32/include
QMAKE_LIBS_LIBPROXY = -lproxy
