set(CMAKE_SYSTEM_NAME Windows)
set(MSYS 1)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_FIND_ROOT_PATH /scratch/build/mxe-octave-w64/usr/x86_64-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_C_COMPILER /scratch/build/mxe-octave-w64/usr/bin/x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER /scratch/build/mxe-octave-w64/usr/bin/x86_64-w64-mingw32-g++)
set(CMAKE_Fortran_COMPILER /scratch/build/mxe-octave-w64/usr/bin/x86_64-w64-mingw32-gfortran)
set(CMAKE_RC_COMPILER /scratch/build/mxe-octave-w64/usr/bin/x86_64-w64-mingw32-windres)
set(PKG_CONFIG_EXECUTABLE /scratch/build/mxe-octave-w64/usr/bin/pkg-config)
set(QT_QMAKE_EXECUTABLE /scratch/build/mxe-octave-w64/usr/x86_64-w64-mingw32/qt6/bin/qmake)
set(CMAKE_INSTALL_PREFIX /scratch/build/mxe-octave-w64/usr/x86_64-w64-mingw32 CACHE PATH "Installation Prefix")
set(CMAKE_INSTALL_LIBDIR "lib")
set(CMAKE_BUILD_TYPE Release CACHE STRING "Debug|Release|RelWithDebInfo|MinSizeRel")
